cmake_minimum_required(VERSION 3.25)
project(PFCheck CXX C)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(ENABLE_SIMD OFF)
find_package(Threads REQUIRED)
set(Python3_EXECUTABLE python3)
set(PF ${CMAKE_CURRENT_SOURCE_DIR}/../pf)
add_library(PokeFinderIncludes INTERFACE)
target_include_directories(PokeFinderIncludes INTERFACE ${PF})
add_subdirectory(${PF}/Core core)
add_executable(pfcheck main.cpp)
target_link_libraries(pfcheck PRIVATE PokeFinderCore Threads::Threads)
add_executable(pfdbg dbg.cpp)
target_link_libraries(pfdbg PRIVATE PokeFinderCore Threads::Threads)
